// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: inspector.proto

package inspectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePaths     []string               `protobuf:"bytes,1,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *InspectRequest) GetFilePaths() []string {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

type VideoDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps           string                 `protobuf:"bytes,3,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoDetails) Reset() {
	*x = VideoDetails{}
	mi := &file_inspector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetails) ProtoMessage() {}

func (x *VideoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetails.ProtoReflect.Descriptor instead.
func (*VideoDetails) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{1}
}

func (x *VideoDetails) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoDetails) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoDetails) GetFps() string {
	if x != nil {
		return x.Fps
	}
	return ""
}

type AudioDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      uint32                 `protobuf:"varint,1,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDetails) Reset() {
	*x = AudioDetails{}
	mi := &file_inspector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDetails) ProtoMessage() {}

func (x *AudioDetails) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDetails.ProtoReflect.Descriptor instead.
func (*AudioDetails) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{2}
}

func (x *AudioDetails) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioDetails) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type Stream struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Codec   string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`
	Bitrate uint32                 `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*Stream_Video
	//	*Stream_Audio
	Details       isStream_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_inspector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{3}
}

func (x *Stream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Stream) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *Stream) GetDetails() isStream_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Stream) GetVideo() *VideoDetails {
	if x != nil {
		if x, ok := x.Details.(*Stream_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *Stream) GetAudio() *AudioDetails {
	if x != nil {
		if x, ok := x.Details.(*Stream_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isStream_Details interface {
	isStream_Details()
}

type Stream_Video struct {
	Video *VideoDetails `protobuf:"bytes,3,opt,name=video,proto3,oneof"`
}

type Stream_Audio struct {
	Audio *AudioDetails `protobuf:"bytes,4,opt,name=audio,proto3,oneof"`
}

func (*Stream_Video) isStream_Details() {}

func (*Stream_Audio) isStream_Details() {}

// FileResult holds the outcome of inspecting a single file.
type FileResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilePath        string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Container       string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Streams         []*Stream              `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileResult) Reset() {
	*x = FileResult{}
	mi := &file_inspector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResult) ProtoMessage() {}

func (x *FileResult) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResult.ProtoReflect.Descriptor instead.
func (*FileResult) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{4}
}

func (x *FileResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileResult) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *FileResult) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *FileResult) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *FileResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FileResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_inspector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{5}
}

func (x *InspectResponse) GetResults() []*FileResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_inspector_proto protoreflect.FileDescriptor

const file_inspector_proto_rawDesc = "" +
	"\n" +
	"\x0finspector.proto\x12\tinspector\"/\n" +
	"\x0eInspectRequest\x12\x1d\n" +
	"\n" +
	"file_paths\x18\x01 \x03(\tR\tfilePaths\"N\n" +
	"\fVideoDetails\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\tR\x03fps\"K\n" +
	"\fAudioDetails\x12\x1a\n" +
	"\bchannels\x18\x01 \x01(\rR\bchannels\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\"\xa5\x01\n" +
	"\x06Stream\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x18\n" +
	"\abitrate\x18\x02 \x01(\rR\abitrate\x12/\n" +
	"\x05video\x18\x03 \x01(\v2\x17.inspector.VideoDetailsH\x00R\x05video\x12/\n" +
	"\x05audio\x18\x04 \x01(\v2\x17.inspector.AudioDetailsH\x00R\x05audioB\t\n" +
	"\adetails\"\xb5\x01\n" +
	"\n" +
	"FileResult\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x01R\x0fdurationSeconds\x12+\n" +
	"\astreams\x18\x04 \x03(\v2\x11.inspector.StreamR\astreams\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"B\n" +
	"\x0fInspectResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.inspector.FileResultR\aresults2R\n" +
	"\x0eMediaInspector\x12@\n" +
	"\aInspect\x12\x19.inspector.InspectRequest\x1a\x1a.inspector.InspectResponseB#Z!media-inspector/proto/inspectorpbb\x06proto3"

var (
	file_inspector_proto_rawDescOnce sync.Once
	file_inspector_proto_rawDescData []byte
)

func file_inspector_proto_rawDescGZIP() []byte {
	file_inspector_proto_rawDescOnce.Do(func() {
		file_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inspector_proto_rawDesc), len(file_inspector_proto_rawDesc)))
	})
	return file_inspector_proto_rawDescData
}

var file_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inspector_proto_goTypes = []any{
	(*InspectRequest)(nil),  // 0: inspector.InspectRequest
	(*VideoDetails)(nil),    // 1: inspector.VideoDetails
	(*AudioDetails)(nil),    // 2: inspector.AudioDetails
	(*Stream)(nil),          // 3: inspector.Stream
	(*FileResult)(nil),      // 4: inspector.FileResult
	(*InspectResponse)(nil), // 5: inspector.InspectResponse
}
var file_inspector_proto_depIdxs = []int32{
	1, // 0: inspector.Stream.video:type_name -> inspector.VideoDetails
	2, // 1: inspector.Stream.audio:type_name -> inspector.AudioDetails
	3, // 2: inspector.FileResult.streams:type_name -> inspector.Stream
	4, // 3: inspector.InspectResponse.results:type_name -> inspector.FileResult
	0, // 4: inspector.MediaInspector.Inspect:input_type -> inspector.InspectRequest
	5, // 5: inspector.MediaInspector.Inspect:output_type -> inspector.InspectResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inspector_proto_init() }
func file_inspector_proto_init() {
	if File_inspector_proto != nil {
		return
	}
	file_inspector_proto_msgTypes[3].OneofWrappers = []any{
		(*Stream_Video)(nil),
		(*Stream_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inspector_proto_rawDesc), len(file_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inspector_proto_goTypes,
		DependencyIndexes: file_inspector_proto_depIdxs,
		MessageInfos:      file_inspector_proto_msgTypes,
	}.Build()
	File_inspector_proto = out.File
	file_inspector_proto_goTypes = nil
	file_inspector_proto_depIdxs = nil
}
