// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: inspector.proto

package inspectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaInspector_Inspect_FullMethodName = "/inspector.MediaInspector/Inspect"
)

// MediaInspectorClient is the client API for MediaInspector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaInspector inspects one or more media files and reports each
// one's container, duration, and per-stream (video/audio) details.
type MediaInspectorClient interface {
	// Inspect analyzes every file path given in the request. The
	// server processes all of them concurrently and returns a single
	// response only once every file has finished, with one FileResult
	// per input path, in the same order they were requested.
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
}

type mediaInspectorClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaInspectorClient(cc grpc.ClientConnInterface) MediaInspectorClient {
	return &mediaInspectorClient{cc}
}

func (c *mediaInspectorClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, MediaInspector_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaInspectorServer is the server API for MediaInspector service.
// All implementations must embed UnimplementedMediaInspectorServer
// for forward compatibility.
//
// MediaInspector inspects one or more media files and reports each
// one's container, duration, and per-stream (video/audio) details.
type MediaInspectorServer interface {
	// Inspect analyzes every file path given in the request. The
	// server processes all of them concurrently and returns a single
	// response only once every file has finished, with one FileResult
	// per input path, in the same order they were requested.
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
	mustEmbedUnimplementedMediaInspectorServer()
}

// UnimplementedMediaInspectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaInspectorServer struct{}

func (UnimplementedMediaInspectorServer) Inspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedMediaInspectorServer) mustEmbedUnimplementedMediaInspectorServer() {}
func (UnimplementedMediaInspectorServer) testEmbeddedByValue()                        {}

// UnsafeMediaInspectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaInspectorServer will
// result in compilation errors.
type UnsafeMediaInspectorServer interface {
	mustEmbedUnimplementedMediaInspectorServer()
}

func RegisterMediaInspectorServer(s grpc.ServiceRegistrar, srv MediaInspectorServer) {
	// If the following call panics, it indicates UnimplementedMediaInspectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaInspector_ServiceDesc, srv)
}

func _MediaInspector_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaInspectorServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaInspector_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaInspectorServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaInspector_ServiceDesc is the grpc.ServiceDesc for MediaInspector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaInspector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inspector.MediaInspector",
	HandlerType: (*MediaInspectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inspect",
			Handler:    _MediaInspector_Inspect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inspector.proto",
}
