// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: inspector.proto

package inspectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *InspectRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Codec         string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Fps           string                 `protobuf:"bytes,5,opt,name=fps,proto3" json:"fps,omitempty"`
	Channels      uint32                 `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,7,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Bitrate       uint32                 `protobuf:"varint,8,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_inspector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{1}
}

func (x *Stream) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Stream) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Stream) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Stream) GetFps() string {
	if x != nil {
		return x.Fps
	}
	return ""
}

func (x *Stream) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *Stream) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *Stream) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type InspectResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Container       string                 `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Streams         []*Stream              `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_inspector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_inspector_proto_rawDescGZIP(), []int{2}
}

func (x *InspectResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *InspectResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *InspectResponse) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

var File_inspector_proto protoreflect.FileDescriptor

const file_inspector_proto_rawDesc = "" +
	"\n" +
	"\x0finspector.proto\x12\tinspector\"-\n" +
	"\x0eInspectRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xc9\x01\n" +
	"\x06Stream\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x05 \x01(\tR\x03fps\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\rR\bchannels\x12\x1f\n" +
	"\vsample_rate\x18\a \x01(\rR\n" +
	"sampleRate\x12\x18\n" +
	"\abitrate\x18\b \x01(\rR\abitrate\"\x87\x01\n" +
	"\x0fInspectResponse\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x01R\x0fdurationSeconds\x12+\n" +
	"\astreams\x18\x03 \x03(\v2\x11.inspector.StreamR\astreams2R\n" +
	"\x0eMediaInspector\x12@\n" +
	"\aInspect\x12\x19.inspector.InspectRequest\x1a\x1a.inspector.InspectResponseB#Z!media-inspector/proto/inspectorpbb\x06proto3"

var (
	file_inspector_proto_rawDescOnce sync.Once
	file_inspector_proto_rawDescData []byte
)

func file_inspector_proto_rawDescGZIP() []byte {
	file_inspector_proto_rawDescOnce.Do(func() {
		file_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inspector_proto_rawDesc), len(file_inspector_proto_rawDesc)))
	})
	return file_inspector_proto_rawDescData
}

var file_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inspector_proto_goTypes = []any{
	(*InspectRequest)(nil),  // 0: inspector.InspectRequest
	(*Stream)(nil),          // 1: inspector.Stream
	(*InspectResponse)(nil), // 2: inspector.InspectResponse
}
var file_inspector_proto_depIdxs = []int32{
	1, // 0: inspector.InspectResponse.streams:type_name -> inspector.Stream
	0, // 1: inspector.MediaInspector.Inspect:input_type -> inspector.InspectRequest
	2, // 2: inspector.MediaInspector.Inspect:output_type -> inspector.InspectResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inspector_proto_init() }
func file_inspector_proto_init() {
	if File_inspector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inspector_proto_rawDesc), len(file_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inspector_proto_goTypes,
		DependencyIndexes: file_inspector_proto_depIdxs,
		MessageInfos:      file_inspector_proto_msgTypes,
	}.Build()
	File_inspector_proto = out.File
	file_inspector_proto_goTypes = nil
	file_inspector_proto_depIdxs = nil
}
